# Generated by Django 6.0.4 on 2026-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('level', models.CharField(default='INFO', max_length=20)),
            ],
        ),
    ]
