# Generated by Django 6.0.4 on 2026-04-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('pattern', 'Pattern'), ('threshold', 'Threshold'), ('behavior', 'Behavioral'), ('ml', 'ML')], default='pattern', max_length=20)),
                ('condition', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('action', models.CharField(choices=[('alert', 'Alert'), ('block', 'Block'), ('notify', 'Notify'), ('log', 'Log Only')], default='alert', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(blank=True, max_length=100)),
                ('value', models.FloatField(default=50)),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('alert_on', models.CharField(choices=[('exceed', 'Exceeds Value'), ('drop', 'Below Value'), ('deviation', 'Deviation')], default='exceed', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(default='unknown', max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly', to='api.log')),
            ],
        ),
    ]
