# Generated by Django 6.0.4 on 2026-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rule_threshold_anomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('confirmed', 'Confirmed Threat'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
