# Generated by Django 6.0.4 on 2026-04-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_anomaly_status_anomaly_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='time_window',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
