# Generated by Django 6.0.4 on 2026-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_rule_time_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='attack_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='bytes_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='dst_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('BRUTE_FORCE', 'Brute Force'), ('SQL_INJECTION', 'SQL Injection'), ('XSS_ATTACK', 'XSS Attack'), ('PORT_SCAN', 'Port Scan'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('EXPLOIT_ATTEMPT', 'Exploit Attempt'), ('MALWARE_ACTIVITY', 'Malware Activity'), ('DDOS_ATTACK', 'DDoS Attack'), ('FIREWALL_BLOCK', 'Firewall Block'), ('RECONNAISSANCE', 'Reconnaissance'), ('BACKDOOR', 'Backdoor'), ('SHELLCODE', 'Shellcode'), ('FUZZER', 'Fuzzer'), ('WORM', 'Worm'), ('DOS_ATTACK', 'DoS Attack'), ('CONFIG_CHANGE', 'Config Change'), ('FILE_ACCESS', 'File Access'), ('GENERIC_ATTACK', 'Generic Attack'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30),
        ),
        migrations.AddField(
            model_name='log',
            name='packets_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='protocol',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='log',
            name='service',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='log',
            name='src_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='state',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
