# Generated by Django 6.0.4 on 2026-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_structured_log_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='anomaly_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='log',
            name='if_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='log',
            name='rf_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='low', max_length=10),
        ),
    ]
