# Generated by Django 5.2.1 on 2026-06-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_log_process_fields_correlatedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='response_time_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
