# Generated by Django 5.2.1 on 2026-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_dataset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlatedevent',
            name='severity',
            field=models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFORMATIONAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFORMATIONAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
