import {
  AIDecision,
  AIModel,
  AlertRecord,
  Anomaly,
  DetectionRule,
  LogEntry,
  Threshold,
} from './types';

const now = new Date('2026-04-23T09:00:00.000Z');

const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const logs: LogEntry[] = [
  {
    id: 'log-1',
    timestamp: hoursAgo(1),
    source: 'Firewall-Gateway',
    event_type: 'failed_login_burst',
    severity: 'high',
    message: '12 failed VPN logins from 185.23.44.10 for user grace.admin',
    user_id: 'grace.admin',
    host_id: 'vpn-gateway-01',
    entity_name: 'Grace Admin',
    status: 'new',
    risk_score: 88,
    metadata: { ip: '185.23.44.10', count: 12, geo: 'Unknown' },
  },
  {
    id: 'log-2',
    timestamp: hoursAgo(1),
    source: 'Firewall-Gateway',
    event_type: 'failed_login_burst',
    severity: 'high',
    message: '12 failed VPN logins from 185.23.44.10 for user grace.admin',
    user_id: 'grace.admin',
    host_id: 'vpn-gateway-01',
    entity_name: 'Grace Admin',
    duplicate_of: 'log-1',
    status: 'new',
    risk_score: 88,
    metadata: { ip: '185.23.44.10', count: 12, geo: 'Unknown' },
  },
  {
    id: 'log-3',
    timestamp: hoursAgo(3),
    source: 'EDR-Server',
    event_type: 'privilege_escalation',
    severity: 'critical',
    message: 'Unsigned process attempted privilege escalation on finance-app-02',
    user_id: 'svc-finance',
    host_id: 'finance-app-02',
    entity_name: 'Finance Service',
    status: 'investigating',
    risk_score: 96,
    metadata: { process: 'unknown.exe', hash: '4af9' },
  },
  {
    id: 'log-4',
    timestamp: hoursAgo(6),
    source: 'CloudTrail',
    event_type: 'impossible_travel',
    severity: 'medium',
    message: 'User analyst.mary logged in from Nairobi and Frankfurt within 20 minutes',
    user_id: 'analyst.mary',
    host_id: 'aws-console',
    entity_name: 'Mary Analyst',
    status: 'new',
    risk_score: 72,
    metadata: { first_geo: 'Nairobi', second_geo: 'Frankfurt' },
  },
  {
    id: 'log-5',
    timestamp: hoursAgo(9),
    source: 'Windows-DC',
    event_type: 'group_membership_change',
    severity: 'medium',
    message: 'Temporary admin rights granted to helpdesk.john',
    user_id: 'helpdesk.john',
    host_id: 'dc-01',
    entity_name: 'John Helpdesk',
    status: 'resolved',
    risk_score: 58,
    metadata: { group: 'Domain Admins', duration: '15m' },
  },
  {
    id: 'log-6',
    timestamp: daysAgo(1),
    source: 'Web-Proxy',
    event_type: 'data_exfiltration_pattern',
    severity: 'high',
    message: 'Large outbound transfer to unsanctioned storage domain',
    user_id: 'intern.sam',
    host_id: 'laptop-443',
    entity_name: 'Sam Intern',
    status: 'investigating',
    risk_score: 84,
    metadata: { mb_sent: 512, domain: 'drop-share.example' },
  },
  {
    id: 'log-7',
    timestamp: daysAgo(2),
    source: 'Kubernetes-Audit',
    event_type: 'config_change',
    severity: 'low',
    message: 'Deployment scaled from 4 to 6 replicas in monitoring namespace',
    user_id: 'platform.bot',
    host_id: 'cluster-prod-1',
    entity_name: 'Platform Bot',
    status: 'resolved',
    risk_score: 22,
    metadata: { namespace: 'monitoring', replicas: 6 },
  },
];

export const rules: DetectionRule[] = [
  {
    id: 'rule-1',
    name: 'VPN Burst Failures',
    description: 'Detect repeated authentication failures from a single IP in a short window.',
    enabled: true,
    rule_type: 'threshold',
    condition: 'failed_login_burst >= 10 in 5m',
    severity: 'high',
    action: 'alert',
    false_positive_rate: 12,
    trigger_count: 34,
  },
  {
    id: 'rule-2',
    name: 'Privilege Escalation on Critical Server',
    description: 'Escalate any privilege change on finance and identity systems.',
    enabled: true,
    rule_type: 'pattern',
    condition: 'event_type == privilege_escalation AND host criticality >= high',
    severity: 'critical',
    action: 'block',
    false_positive_rate: 4,
    trigger_count: 9,
  },
  {
    id: 'rule-3',
    name: 'Impossible Travel',
    description: 'Detect impossible travel based on last known login locations.',
    enabled: true,
    rule_type: 'behavior',
    condition: 'geo_distance / login_time_delta > travel_baseline',
    severity: 'medium',
    action: 'notify',
    false_positive_rate: 18,
    trigger_count: 27,
  },
];

export const thresholds: Threshold[] = [
  {
    id: 'threshold-1',
    name: 'Duplicate Suppression Window',
    description: 'Window used to collapse repeated copies of the same event before AI analysis.',
    value: 10,
    unit: 'minutes',
    enabled: true,
    alert_on: 'exceed',
  },
  {
    id: 'threshold-2',
    name: 'Behavior Risk Trigger',
    description: 'Minimum calculated behavior risk score that creates an analyst-visible anomaly.',
    value: 70,
    unit: 'score',
    enabled: true,
    alert_on: 'exceed',
  },
  {
    id: 'threshold-3',
    name: 'AI Auto-Dismiss Confidence',
    description: 'Confidence required for AI to auto-dismiss likely benign noise.',
    value: 82,
    unit: 'percent',
    enabled: true,
    alert_on: 'exceed',
  },
];

export const aiModels: AIModel[] = [
  {
    id: 'model-1',
    name: 'False Positive Reducer',
    version: '2.3.1',
    model_type: 'Ensemble',
    status: 'active',
    is_active: true,
    accuracy: 89,
    last_updated: daysAgo(3),
    weights: { duplicatePenalty: 0.42, behaviorAnomaly: 0.86, ruleSeverity: 0.73, assetCriticality: 0.78 },
    false_positive_reduction: 31,
  },
  {
    id: 'model-2',
    name: 'Behavior Baseline Model',
    version: '1.8.0',
    model_type: 'Behavioral',
    status: 'shadow',
    is_active: false,
    accuracy: 81,
    last_updated: daysAgo(7),
    weights: { geoVelocity: 0.61, accessTime: 0.44, privilegeJump: 0.82, dataTransfer: 0.75 },
    false_positive_reduction: 19,
  },
];

export const aiDecisions: AIDecision[] = [
  {
    id: 'decision-1',
    timestamp: hoursAgo(1),
    event_description: 'Repeated VPN failures for grace.admin matched duplicate burst suppression and retained one high-risk event.',
    decision: 'threat',
    secondary_decision: 'deduplicate-then-escalate',
    confidence: 91,
    model_id: 'model-1',
    model_name: 'False Positive Reducer',
    status: 'confirmed',
  },
  {
    id: 'decision-2',
    timestamp: hoursAgo(6),
    event_description: 'Impossible travel for analyst.mary classified as medium priority pending analyst review.',
    decision: 'threat',
    secondary_decision: 'behavior-anomaly',
    confidence: 74,
    model_id: 'model-2',
    model_name: 'Behavior Baseline Model',
    status: 'pending',
  },
  {
    id: 'decision-3',
    timestamp: daysAgo(2),
    event_description: 'Replica count change in monitoring namespace classified as benign operational drift.',
    decision: 'benign',
    secondary_decision: 'known-change-window',
    confidence: 87,
    model_id: 'model-1',
    model_name: 'False Positive Reducer',
    status: 'overridden',
    override_reason: 'Ops confirmed this was a planned production scaling event.',
    human_decision: 'benign',
  },
];

export const alerts: AlertRecord[] = [
  {
    id: 'alert-1',
    timestamp: hoursAgo(1),
    severity: 'high',
    source: 'Firewall-Gateway',
    alert_type: 'authentication_anomaly',
    message: 'Burst login failures survived deduplication and exceeded risk threshold.',
    status: 'open',
    log_id: 'log-1',
    ai_decision_id: 'decision-1',
    confidence: 91,
  },
  {
    id: 'alert-2',
    timestamp: hoursAgo(3),
    severity: 'critical',
    source: 'EDR-Server',
    alert_type: 'privilege_escalation',
    message: 'Unsigned process attempted elevation on finance-app-02.',
    status: 'acknowledged',
    log_id: 'log-3',
    ai_decision_id: 'decision-1',
    confidence: 96,
  },
  {
    id: 'alert-3',
    timestamp: hoursAgo(6),
    severity: 'medium',
    source: 'CloudTrail',
    alert_type: 'behavior_deviation',
    message: 'Impossible travel needs analyst validation.',
    status: 'open',
    log_id: 'log-4',
    ai_decision_id: 'decision-2',
    confidence: 74,
  },
];

export const anomalies: Anomaly[] = [
  {
    id: 'anomaly-1',
    timestamp: hoursAgo(6),
    entity_name: 'Mary Analyst',
    anomaly_type: 'Impossible Travel',
    risk_level: 'medium',
    confidence: 74,
    user_id: 'analyst.mary',
    host_id: 'aws-console',
    description: 'The user authenticated from two distant geographies in an implausibly short time window.',
    summary: 'Travel velocity far above baseline between two sign-ins.',
    recommended_action: 'Require MFA revalidation and review access token issuance.',
    details: { first_login_gap_minutes: 20, baseline_minutes: 420 },
  },
  {
    id: 'anomaly-2',
    timestamp: hoursAgo(9),
    entity_name: 'Sam Intern',
    anomaly_type: 'Abnormal Data Transfer',
    risk_level: 'high',
    confidence: 86,
    user_id: 'intern.sam',
    host_id: 'laptop-443',
    description: 'Outbound transfer volume and destination type exceeded the user peer baseline.',
    summary: 'Outbound data transfer volume exceeded peer baseline by 6.4x.',
    recommended_action: 'Quarantine endpoint and review outbound destinations.',
    details: { outbound_megabytes: 512, baseline_multiplier: 6.4 },
  },
  {
    id: 'anomaly-3',
    timestamp: hoursAgo(3),
    entity_name: 'Finance Service',
    anomaly_type: 'Privilege Escalation',
    risk_level: 'critical',
    confidence: 96,
    user_id: 'svc-finance',
    host_id: 'finance-app-02',
    description: 'Service account activity deviated sharply from its known privilege baseline.',
    summary: 'Privilege escalation attempt deviated from service account baseline.',
    recommended_action: 'Isolate host and rotate service credentials.',
    details: { privilege_jump: 3, known_admin_sessions: 0 },
  },
];
